name: gnome-text-editor
base: core22
grade: stable
confinement: strict
adopt-info: gnome-text-editor

# this is not used or needed for anything other than to trigger automatic
# installation of the cups snap via "default-provider: cups"
plugs:
  foo-install-cups:
    interface: content
    content: foo
    default-provider: cups
    target: $SNAP_DATA/foo

slots:
  # for GtkApplication registration
  gnome-text-editor:
    interface: dbus
    bus: session
    name: org.gnome.TextEditor

layout:
  /usr/share/gnome-text-editor:
    bind: $SNAP/usr/share/gnome-text-editor

apps:
  gnome-text-editor:
    extensions: [gnome]
    command: usr/bin/gnome-text-editor
    desktop: usr/share/applications/org.gnome.TextEditor.desktop
    common-id: org.gnome.TextEditor.desktop
    environment:
      GTK_USE_PORTAL: "1"
      GDK_DEBUG: "portals"
    plugs:
      - home
      - removable-media
      - mount-observe
      - cups

parts:
  gnome-text-editor:
# ext:updatesnap
    source: https://gitlab.gnome.org/GNOME/gnome-text-editor.git
    source-tag: '45.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dbugreport_url=https://github.com/ubuntu/gnome-text-editor/issues
    parse-info: [usr/share/metainfo/org.gnome.TextEditor.appdata.xml]
    build-packages:
      - libeditorconfig-dev
      - libfreetype6
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)

  libraries:
    after: [ gnome-text-editor ]
    plugin: nil
    stage-packages:
      - libeditorconfig0
    prime:
      - usr/lib/*/libeditorconfig.so.*
