name: gnome-text-editor
base: core22
version: '42.2'
summary: A simple text editor
description: |
  The oficial Gnome Text Editor

grade: stable
confinement: strict

slots:
  # for GtkApplication registration
  gnome-text-editor:
    interface: dbus
    bus: session
    name: org.gnome.TextEditor

layout:
  /usr/share/gnome-text-editor:
    bind: $SNAP/usr/share/gnome-text-editor

apps:
  gnome-text-editor:
    extensions: [gnome]
    command: usr/bin/gnome-text-editor
    desktop: usr/share/applications/org.gnome.TextEditor.desktop
    plugs:
      - gsettings
      - mount-observe

parts:
  gnome-text-editor:
    source: https://gitlab.gnome.org/GNOME/gnome-text-editor
    source-tag: '42.2'
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    override-prime: |
      craftctl default
      sed -i.bak -e 's|Icon=org.gnome.TextEditor$|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/org.gnome.TextEditor.svg|g' $CRAFT_PRIME/usr/share/applications/org.gnome.TextEditor.desktop
      for i in $CRAFT_PRIME/usr/share/icons/*;
      do
        if [ -f $i/index.theme ];
        then
          echo Updating cache at $i
          gtk-update-icon-cache $i
        fi
      done
