name: gnome-text-editor
base: core22
grade: stable
confinement: strict
adopt-info: gnome-text-editor

# this is not used or needed for anything other than to trigger automatic
# installation of the cups snap via "default-provider: cups"
plugs:
  foo-install-cups:
    interface: content
    content: foo
    default-provider: cups
    target: $SNAP_DATA/foo

slots:
  # for GtkApplication registration
  gnome-text-editor:
    interface: dbus
    bus: session
    name: org.gnome.TextEditor

layout:
  /usr/share/gnome-text-editor:
    bind: $SNAP/usr/share/gnome-text-editor

apps:
  gnome-text-editor:
    extensions: [gnome]
    command: usr/bin/gnome-text-editor
    desktop: usr/share/applications/org.gnome.TextEditor.desktop
    common-id: org.gnome.TextEditor.desktop
    plugs:
      - gsettings
      - mount-observe
      - cups

parts:
  gnome-text-editor:
    source: https://gitlab.gnome.org/GNOME/gnome-text-editor
    source-tag: '43.1'
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    parse-info: [usr/share/metainfo/org.gnome.TextEditor.appdata.xml]
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
      sed -i.bak -e 's|Icon=@app_id@$|Icon=snap.gnome-text-editor.icon|g' data/org.gnome.TextEditor.desktop.in.in
    override-build: |
      craftctl default
      mkdir -p ${CRAFT_PART_INSTALL}/meta/gui/icons/hicolor/scalable/apps
      cp ../src/data/icons/org.gnome.TextEditor.svg ${CRAFT_PART_INSTALL}/meta/gui/icons/hicolor/scalable/apps/snap.gnome-text-editor.icon.svg
    override-prime: |
      craftctl default
      for i in $CRAFT_PRIME/usr/share/icons/*;
      do
        if [ -f $i/index.theme ];
        then
          echo Updating cache at $i
          gtk-update-icon-cache $i
        fi
      done
